# Автосгенерировано convert_sprites.py -- НЕ редактировать руками.
# Формат строки: (zoom_tuple, kind, "имя картинки", (относительные_пути_слоёв,))
#   zoom_tuple: любое подмножество ("far","normal","close") -- какие варианты генерировать
#   kind: "day" | "night" | "red" | "plain" | ("tint", (r,g,b))

init 2 python in v1FNaSR:
    SPRITES = [
        (('far', 'normal', 'close'), 'day', 'cs normal stethoscope', ('cs/cs_1_body.png', 'cs/cs_1_stethoscope.png', 'cs/cs_1_normal.png')),
        (('far', 'normal', 'close'), 'day', 'dv grin swim', ('dv/dv_2_body.png', 'dv/dv_2_swim.png', 'dv/dv_2_grin.png')),
        (('far', 'normal', 'close'), 'day', 'dv laugh swim', ('dv/dv_4_body.png', 'dv/dv_4_swim.png', 'dv/dv_4_laugh.png')),
        (('far', 'normal', 'close'), 'day', 'dv scared pioneer', ('dv/dv_1_body.png', 'dv/dv_1_pioneer.png', 'dv/dv_1_scared.png')),
        (('far', 'normal', 'close'), 'day', 'sl smile2 sport', ('sl/sl_2_body.png', 'sl/sl_2_sport.png', 'sl/sl_2_smile2.png')),
        (('far', 'normal', 'close'), 'day', 'dv rage pioneer2', ('dv/dv_5_body.png', 'dv/dv_5_pioneer2.png', 'dv/dv_5_rage.png')),
        (('far', 'normal', 'close'), 'day', 'mi scared pioneer', ('mi/mi_1_body.png', 'mi/mi_1_pioneer.png', 'mi/mi_1_scared.png')),
        (('far', 'normal', 'close'), 'day', 'us grin pioneer', ('us/us_1_body.png', 'us/us_1_pioneer.png', 'us/us_1_grin.png')),
        (('far', 'normal', 'close'), 'day', 'un angry swim', ('un/un_1_body.png', 'un/un_1_swim.png', 'un/un_1_angry.png')),
        (('far', 'normal', 'close'), 'day', 'mi happy pioneer', ('mi/mi_2_body.png', 'mi/mi_2_pioneer.png', 'mi/mi_2_happy.png')),
        (('far', 'normal', 'close'), 'day', 'un serious pioneer', ('un/un_3_body.png', 'un/un_3_pioneer.png', 'un/un_3_serious.png')),
        (('far', 'normal', 'close'), 'day', 'us surp2 sport', ('us/us_3_body.png', 'us/us_3_sport.png', 'us/us_3_surp2.png')),
        (('far', 'normal', 'close'), 'day', 'un smile2 dress', ('un/un_1_body.png', 'un/un_1_dress.png', 'un/un_1_smile2.png')),
        (('far', 'normal', 'close'), 'day', 'us surp2 pioneer', ('us/us_3_body.png', 'us/us_3_pioneer.png', 'us/us_3_surp2.png')),
        (('far', 'normal', 'close'), 'day', 'sl shy sport', ('sl/sl_2_body.png', 'sl/sl_2_sport.png', 'sl/sl_2_shy.png')),
        (('far', 'normal', 'close'), 'day', 'cs smile', ('cs/cs_1_body.png', 'cs/cs_1_smile.png')),
        (('far', 'normal', 'close'), 'day', 'mz rage pioneer', ('mz/mz_2_body.png', 'mz/mz_2_pioneer.png', 'mz/mz_2_rage.png')),
        (('far', 'normal', 'close'), 'day', 'un cry sport', ('un/un_2_body.png', 'un/un_2_sport.png', 'un/un_2_cry.png')),
        (('far', 'normal', 'close'), 'day', 'un evil_smile swim', ('un/un_1_body.png', 'un/un_1_swim.png', 'un/un_1_evil_smile.png')),
        (('far', 'normal', 'close'), 'day', 'sh smile pioneer', ('sh/sh_1_body.png', 'sh/sh_1_smile.png')),
        (('far', 'normal', 'close'), 'day', 'us sad swim', ('us/us_1_body.png', 'us/us_1_swim.png', 'us/us_1_sad.png')),
        (('far', 'normal', 'close'), 'day', 'sh cry', ('sh/sh_2_body.png', 'sh/sh_2_rage.png', 'sh/sh_2_cry.png')),
        (('far', 'normal', 'close'), 'day', 'sh surprise pioneer', ('sh/sh_3_body.png', 'sh/sh_3_surprise.png')),
        (('far', 'normal', 'close'), 'day', 'mt grin panama pioneer', ('mt/mt_3_body.png', 'mt/mt_3_panama.png', 'mt/mt_3_grin.png', 'mt/mt_3_pioneer.png')),
        (('far', 'normal', 'close'), 'day', 'dv sad pioneer', ('dv/dv_3_body.png', 'dv/dv_3_pioneer.png', 'dv/dv_3_sad.png')),
        (('far', 'normal', 'close'), 'day', 'mt smile panama swim', ('mt/mt_1_body.png', 'mt/mt_1_panama.png', 'mt/mt_1_smile.png', 'mt/mt_1_swim.png')),
        (('far', 'normal', 'close'), 'day', 'dv cry pioneer2', ('dv/dv_1_body.png', 'dv/dv_1_pioneer2.png', 'dv/dv_1_cry.png')),
        (('far', 'normal', 'close'), 'day', 'mt rage panama pioneer', ('mt/mt_2_body.png', 'mt/mt_2_panama.png', 'mt/mt_2_rage.png', 'mt/mt_2_pioneer.png')),
        (('far', 'normal', 'close'), 'day', 'un smile dress', ('un/un_1_body.png', 'un/un_1_dress.png', 'un/un_1_smile.png')),
        (('far', 'normal', 'close'), 'day', 'mi dontlike swim', ('mi/mi_1_body.png', 'mi/mi_1_swim.png', 'mi/mi_1_dontlike.png')),
        (('far', 'normal', 'close'), 'day', 'un angry2 dress', ('un/un_3_body.png', 'un/un_3_dress.png', 'un/un_3_angry2.png')),
        (('far', 'normal', 'close'), 'day', 'sl serious dress', ('sl/sl_1_body.png', 'sl/sl_1_dress.png', 'sl/sl_1_serious.png')),
        (('far', 'normal', 'close'), 'day', 'dv guilty pioneer', ('dv/dv_3_body.png', 'dv/dv_3_pioneer.png', 'dv/dv_3_guilty.png')),
        (('far', 'normal', 'close'), 'day', 'mz normal pioneer', ('mz/mz_1_body.png', 'mz/mz_1_pioneer.png', 'mz/mz_1_normal.png')),
        (('far', 'normal', 'close'), 'day', 'un cry_smile swim', ('un/un_2_body.png', 'un/un_2_swim.png', 'un/un_2_cry_smile.png')),
        (('far', 'normal', 'close'), 'day', 'uv normal', ('uv/uv_2_body.png', 'uv/uv_2_pioneer.png', 'uv/uv_2_normal.png')),
        (('far', 'normal', 'close'), 'day', 'us angry swim', ('us/us_2_body.png', 'us/us_2_swim.png', 'us/us_2_angry.png')),
        (('far', 'normal', 'close'), 'day', 'mt normal swim', ('mt/mt_1_body.png', 'mt/mt_1_swim.png', 'mt/mt_1_normal.png')),
        (('far', 'normal', 'close'), 'day', 'us dontlike pioneer', ('us/us_2_body.png', 'us/us_2_pioneer.png', 'us/us_2_dontlike.png')),
        (('far', 'normal', 'close'), 'day', 'un normal sport', ('un/un_1_body.png', 'un/un_1_sport.png', 'un/un_1_normal.png')),
        (('far', 'normal', 'close'), 'day', 'un grin sport', ('un/un_3_body.png', 'un/un_3_sport.png', 'un/un_3_grin.png')),
        (('far', 'normal', 'close'), 'day', 'mi laugh pioneer', ('mi/mi_1_body.png', 'mi/mi_1_pioneer.png', 'mi/mi_1_laugh.png')),
        (('far', 'normal', 'close'), 'day', 'un shocked sport', ('un/un_2_body.png', 'un/un_2_sport.png', 'un/un_2_shocked.png')),
        (('far', 'normal', 'close'), 'day', 'us laugh2 dress', ('us/us_1_body.png', 'us/us_1_dress.png', 'us/us_1_laugh2.png')),
        (('far', 'normal', 'close'), 'day', 'el laugh pioneer', ('el/el_3_body.png', 'el/el_3_pioneer.png', 'el/el_3_laugh.png')),
        (('far', 'normal', 'close'), 'day', 'sl tender pioneer', ('sl/sl_4_body.png', 'sl/sl_4_pioneer.png', 'sl/sl_4_tender.png')),
        (('far', 'normal', 'close'), 'day', 'sl smile pioneer', ('sl/sl_1_body.png', 'sl/sl_1_pioneer.png', 'sl/sl_1_smile.png')),
        (('far', 'normal', 'close'), 'day', 'us angry pioneer', ('us/us_2_body.png', 'us/us_2_pioneer.png', 'us/us_2_angry.png')),
        (('far', 'normal', 'close'), 'day', 'sh normal_smile pioneer', ('sh/sh_2_body.png', 'sh/sh_2_normal_smile.png')),
        (('far', 'normal', 'close'), 'day', 'dv laugh pioneer', ('dv/dv_4_body.png', 'dv/dv_4_pioneer.png', 'dv/dv_4_laugh.png')),
        (('far', 'normal', 'close'), 'day', 'us sad dress', ('us/us_1_body.png', 'us/us_1_dress.png', 'us/us_1_sad.png')),
        (('far', 'normal', 'close'), 'day', 'mt rage panama swim', ('mt/mt_2_body.png', 'mt/mt_2_panama.png', 'mt/mt_2_rage.png', 'mt/mt_2_swim.png')),
        (('far', 'normal', 'close'), 'day', 'un angry dress', ('un/un_1_body.png', 'un/un_1_dress.png', 'un/un_1_angry.png')),
        (('far', 'normal', 'close'), 'day', 'un angry pioneer', ('un/un_1_body.png', 'un/un_1_pioneer.png', 'un/un_1_angry.png')),
        (('far', 'normal', 'close'), 'day', 'cs normal', ('cs/cs_1_body.png', 'cs/cs_1_normal.png')),
        (('far', 'normal', 'close'), 'day', 'us upset pioneer', ('us/us_2_body.png', 'us/us_2_pioneer.png', 'us/us_2_upset.png')),
        (('far', 'normal', 'close'), 'day', 'us smile dress', ('us/us_1_body.png', 'us/us_1_dress.png', 'us/us_1_smile.png')),
        (('far', 'normal', 'close'), 'day', 'dv shy pioneer', ('dv/dv_3_body.png', 'dv/dv_3_pioneer.png', 'dv/dv_3_shy.png')),
        (('far', 'normal', 'close'), 'day', 'un smile3 sport', ('un/un_3_body.png', 'un/un_3_sport.png', 'un/un_3_smile3.png')),
        (('far', 'normal', 'close'), 'day', 'un shy sport', ('un/un_1_body.png', 'un/un_1_sport.png', 'un/un_1_shy.png')),
        (('far', 'normal', 'close'), 'day', 'cs smile glasses', ('cs/cs_1_body.png', 'cs/cs_1_glasses.png', 'cs/cs_1_smile.png')),
        (('far', 'normal', 'close'), 'day', 'sl scared sport', ('sl/sl_4_body.png', 'sl/sl_4_sport.png', 'sl/sl_4_scared.png')),
        (('far', 'normal', 'close'), 'day', 'dv shy pioneer2', ('dv/dv_3_body.png', 'dv/dv_3_pioneer2.png', 'dv/dv_3_shy.png')),
        (('far', 'normal', 'close'), 'day', 'us fear swim', ('us/us_2_body.png', 'us/us_2_swim.png', 'us/us_2_fear.png')),
        (('far', 'normal', 'close'), 'day', 'sh smile', ('sh/sh_1_body.png', 'sh/sh_1_laugh.png', 'sh/sh_1_smile.png')),
        (('far', 'normal', 'close'), 'day', 'us fear dress', ('us/us_2_body.png', 'us/us_2_dress.png', 'us/us_2_fear.png')),
        (('far', 'normal', 'close'), 'day', 'mt sad pioneer', ('mt/mt_1_body.png', 'mt/mt_1_pioneer.png', 'mt/mt_1_sad.png')),
        (('far', 'normal', 'close'), 'day', 'mt smile dress', ('mt/mt_1_body.png', 'mt/mt_1_dress.png', 'mt/mt_1_smile.png')),
        (('far', 'normal', 'close'), 'day', 'un smile2 swim', ('un/un_1_body.png', 'un/un_1_swim.png', 'un/un_1_smile2.png')),
        (('far', 'normal', 'close'), 'day', 'sh normal_smile', ('sh/sh_2_body.png', 'sh/sh_2_rage.png', 'sh/sh_2_normal_smile.png')),
        (('far', 'normal', 'close'), 'day', 'sl tender swim', ('sl/sl_4_body.png', 'sl/sl_4_swim.png', 'sl/sl_4_tender.png')),
        (('far', 'normal', 'close'), 'day', 'mt rage pioneer', ('mt/mt_2_body.png', 'mt/mt_2_pioneer.png', 'mt/mt_2_rage.png')),
        (('far', 'normal', 'close'), 'day', 'mt angry panama pioneer', ('mt/mt_2_body.png', 'mt/mt_2_panama.png', 'mt/mt_2_angry.png', 'mt/mt_2_pioneer.png')),
        (('far', 'normal', 'close'), 'day', 'un smile2 pioneer', ('un/un_1_body.png', 'un/un_1_pioneer.png', 'un/un_1_smile2.png')),
        (('far', 'normal', 'close'), 'day', 'el normal pioneer', ('el/el_1_body.png', 'el/el_1_pioneer.png', 'el/el_1_normal.png')),
        (('far', 'normal', 'close'), 'day', 'mt smile panama dress', ('mt/mt_1_body.png', 'mt/mt_1_panama.png', 'mt/mt_1_smile.png', 'mt/mt_1_dress.png')),
        (('far', 'normal', 'close'), 'day', 'sl laugh sport', ('sl/sl_2_body.png', 'sl/sl_2_sport.png', 'sl/sl_2_laugh.png')),
        (('far', 'normal', 'close'), 'day', 'us upset sport', ('us/us_2_body.png', 'us/us_2_sport.png', 'us/us_2_upset.png')),
        (('far', 'normal', 'close'), 'day', 'mt normal pioneer', ('mt/mt_1_body.png', 'mt/mt_1_pioneer.png', 'mt/mt_1_normal.png')),
        (('far', 'normal', 'close'), 'day', 'us cry2 swim', ('us/us_3_body.png', 'us/us_3_swim.png', 'us/us_3_cry2.png')),
        (('far', 'normal', 'close'), 'day', 'mt surprise swim', ('mt/mt_1_body.png', 'mt/mt_1_swim.png', 'mt/mt_1_surprise.png')),
        (('far', 'normal', 'close'), 'day', 'sl smile dress', ('sl/sl_1_body.png', 'sl/sl_1_dress.png', 'sl/sl_1_smile.png')),
        (('far', 'normal', 'close'), 'day', 'us upset swim', ('us/us_2_body.png', 'us/us_2_swim.png', 'us/us_2_upset.png')),
        (('far', 'normal', 'close'), 'day', 'un smile sport', ('un/un_1_body.png', 'un/un_1_sport.png', 'un/un_1_smile.png')),
        (('far', 'normal', 'close'), 'day', 'un smile pioneer', ('un/un_1_body.png', 'un/un_1_pioneer.png', 'un/un_1_smile.png')),
        (('far', 'normal', 'close'), 'day', 'us upset dress', ('us/us_2_body.png', 'us/us_2_dress.png', 'us/us_2_upset.png')),
        (('far', 'normal', 'close'), 'day', 'us laugh pioneer', ('us/us_1_body.png', 'us/us_1_pioneer.png', 'us/us_1_laugh.png')),
        (('far', 'normal', 'close'), 'day', 'un rage sport', ('un/un_3_body.png', 'un/un_3_sport.png', 'un/un_3_rage.png')),
        (('far', 'normal', 'close'), 'day', 'sl scared pioneer', ('sl/sl_4_body.png', 'sl/sl_4_pioneer.png', 'sl/sl_4_scared.png')),
        (('far', 'normal', 'close'), 'day', 'us shy2 sport', ('us/us_3_body.png', 'us/us_3_sport.png', 'us/us_3_shy2.png')),
        (('far', 'normal', 'close'), 'day', 'sl surprise sport', ('sl/sl_3_body.png', 'sl/sl_3_sport.png', 'sl/sl_3_surprise.png')),
        (('far', 'normal', 'close'), 'day', 'us surp1 swim', ('us/us_3_body.png', 'us/us_3_swim.png', 'us/us_3_surp1.png')),
        (('far', 'normal', 'close'), 'day', 'mt angry dress', ('mt/mt_2_body.png', 'mt/mt_2_dress.png', 'mt/mt_2_angry.png')),
        (('far', 'normal', 'close'), 'day', 'uv upset', ('uv/uv_4_body.png', 'uv/uv_4_pioneer.png', 'uv/uv_4_upset.png')),
        (('far', 'normal', 'close'), 'day', 'sh serious', ('sh/sh_3_body.png', 'sh/sh_3_normal.png', 'sh/sh_3_serious.png')),
        (('far', 'normal', 'close'), 'day', 'uv guilty', ('uv/uv_4_body.png', 'uv/uv_4_pioneer.png', 'uv/uv_4_guilty.png')),
        (('far', 'normal', 'close'), 'day', 'us calml swim', ('us/us_2_body.png', 'us/us_2_swim.png', 'us/us_2_calml.png')),
        (('far', 'normal', 'close'), 'day', 'us shy2 swim', ('us/us_3_body.png', 'us/us_3_swim.png', 'us/us_3_shy2.png')),
        (('far', 'normal', 'close'), 'day', 'us dontlike dress', ('us/us_2_body.png', 'us/us_2_dress.png', 'us/us_2_dontlike.png')),
        (('far', 'normal', 'close'), 'day', 'mi smile pioneer', ('mi/mi_2_body.png', 'mi/mi_2_pioneer.png', 'mi/mi_2_smile.png')),
        (('far', 'normal', 'close'), 'day', 'us dontlike sport', ('us/us_2_body.png', 'us/us_2_sport.png', 'us/us_2_dontlike.png')),
        (('far', 'normal', 'close'), 'day', 'un normal pioneer', ('un/un_1_body.png', 'un/un_1_pioneer.png', 'un/un_1_normal.png')),
        (('far', 'normal', 'close'), 'day', 'us cry pioneer', ('us/us_3_body.png', 'us/us_3_pioneer.png', 'us/us_3_cry.png')),
        (('far', 'normal', 'close'), 'day', 'un shy swim', ('un/un_1_body.png', 'un/un_1_swim.png', 'un/un_1_shy.png')),
        (('far', 'normal', 'close'), 'day', 'sl smile2 pioneer', ('sl/sl_2_body.png', 'sl/sl_2_pioneer.png', 'sl/sl_2_smile2.png')),
        (('far', 'normal', 'close'), 'day', 'mi cry_smile pioneer', ('mi/mi_2_body.png', 'mi/mi_2_pioneer.png', 'mi/mi_2_cry_smile.png')),
        (('far', 'normal', 'close'), 'day', 'un normal swim', ('un/un_1_body.png', 'un/un_1_swim.png', 'un/un_1_normal.png')),
        (('far', 'normal', 'close'), 'day', 'dv normal swim', ('dv/dv_4_body.png', 'dv/dv_4_swim.png', 'dv/dv_4_normal.png')),
        (('far', 'normal', 'close'), 'day', 'un scared pioneer', ('un/un_2_body.png', 'un/un_2_pioneer.png', 'un/un_2_scared.png')),
        (('far', 'normal', 'close'), 'day', 'dv smile pioneer', ('dv/dv_4_body.png', 'dv/dv_4_pioneer.png', 'dv/dv_4_smile.png')),
        (('far', 'normal', 'close'), 'day', 'us shy swim', ('us/us_3_body.png', 'us/us_3_swim.png', 'us/us_3_shy.png')),
        (('far', 'normal', 'close'), 'day', 'cs shy glasses', ('cs/cs_1_body.png', 'cs/cs_1_glasses.png', 'cs/cs_1_shy.png')),
        (('far', 'normal', 'close'), 'day', 'cs smile stethoscope', ('cs/cs_1_body.png', 'cs/cs_1_stethoscope.png', 'cs/cs_1_smile.png')),
        (('far', 'normal', 'close'), 'day', 'us grin swim', ('us/us_1_body.png', 'us/us_1_swim.png', 'us/us_1_grin.png')),
        (('far', 'normal', 'close'), 'day', 'sl normal dress', ('sl/sl_1_body.png', 'sl/sl_1_dress.png', 'sl/sl_1_normal.png')),
        (('far', 'normal', 'close'), 'day', 'mi cry pioneer', ('mi/mi_1_body.png', 'mi/mi_1_pioneer.png', 'mi/mi_1_cry.png')),
        (('far', 'normal', 'close'), 'day', 'mt grin pioneer', ('mt/mt_3_body.png', 'mt/mt_3_pioneer.png', 'mt/mt_3_grin.png')),
        (('far', 'normal', 'close'), 'day', 'mt surprise pioneer', ('mt/mt_1_body.png', 'mt/mt_1_pioneer.png', 'mt/mt_1_surprise.png')),
        (('far', 'normal', 'close'), 'day', 'dv smile swim', ('dv/dv_4_body.png', 'dv/dv_4_swim.png', 'dv/dv_4_smile.png')),
        (('far', 'normal', 'close'), 'day', 'un laugh dress', ('un/un_3_body.png', 'un/un_3_dress.png', 'un/un_3_laugh.png')),
        (('far', 'normal', 'close'), 'day', 'sl serious pioneer', ('sl/sl_1_body.png', 'sl/sl_1_pioneer.png', 'sl/sl_1_serious.png')),
        (('far', 'normal', 'close'), 'day', 'us smile sport', ('us/us_1_body.png', 'us/us_1_sport.png', 'us/us_1_smile.png')),
        (('far', 'normal', 'close'), 'day', 'sh serious pioneer', ('sh/sh_3_body.png', 'sh/sh_3_serious.png')),
        (('far', 'normal', 'close'), 'day', 'un serious sport', ('un/un_3_body.png', 'un/un_3_sport.png', 'un/un_3_serious.png')),
        (('far', 'normal', 'close'), 'day', 'mt normal panama pioneer', ('mt/mt_1_body.png', 'mt/mt_1_panama.png', 'mt/mt_1_normal.png', 'mt/mt_1_pioneer.png')),
        (('far', 'normal', 'close'), 'day', 'mt sad panama dress', ('mt/mt_1_body.png', 'mt/mt_1_panama.png', 'mt/mt_1_sad.png', 'mt/mt_1_dress.png')),
        (('far', 'normal', 'close'), 'day', 'sl angry dress', ('sl/sl_3_body.png', 'sl/sl_3_dress.png', 'sl/sl_3_angry.png')),
        (('far', 'normal', 'close'), 'day', 'sl surprise dress', ('sl/sl_3_body.png', 'sl/sl_3_dress.png', 'sl/sl_3_surprise.png')),
        (('far', 'normal', 'close'), 'day', 'dv shocked pioneer', ('dv/dv_1_body.png', 'dv/dv_1_pioneer.png', 'dv/dv_1_shocked.png')),
        (('far', 'normal', 'close'), 'day', 'us surp2 swim', ('us/us_3_body.png', 'us/us_3_swim.png', 'us/us_3_surp2.png')),
        (('far', 'normal', 'close'), 'day', 'sl tender sport', ('sl/sl_4_body.png', 'sl/sl_4_sport.png', 'sl/sl_4_tender.png')),
        (('far', 'normal', 'close'), 'day', 'sl surprise pioneer', ('sl/sl_3_body.png', 'sl/sl_3_pioneer.png', 'sl/sl_3_surprise.png')),
        (('far', 'normal', 'close'), 'day', 'us grin sport', ('us/us_1_body.png', 'us/us_1_sport.png', 'us/us_1_grin.png')),
        (('far', 'normal', 'close'), 'day', 'us laugh2 swim', ('us/us_1_body.png', 'us/us_1_swim.png', 'us/us_1_laugh2.png')),
        (('far', 'normal', 'close'), 'day', 'dv guilty pioneer2', ('dv/dv_3_body.png', 'dv/dv_3_pioneer2.png', 'dv/dv_3_guilty.png')),
        (('far', 'normal', 'close'), 'day', 'sl smile2 swim', ('sl/sl_2_body.png', 'sl/sl_2_swim.png', 'sl/sl_2_smile2.png')),
        (('far', 'normal', 'close'), 'day', 'mi normal swim', ('mi/mi_3_body.png', 'mi/mi_3_swim.png', 'mi/mi_3_normal.png')),
        (('far', 'normal', 'close'), 'day', 'sl normal sport', ('sl/sl_1_body.png', 'sl/sl_1_sport.png', 'sl/sl_1_normal.png')),
        (('far', 'normal', 'close'), 'day', 'mi sad pioneer', ('mi/mi_2_body.png', 'mi/mi_2_pioneer.png', 'mi/mi_2_sad.png')),
        (('far', 'normal', 'close'), 'day', 'un smile3 pioneer', ('un/un_3_body.png', 'un/un_3_pioneer.png', 'un/un_3_smile3.png')),
        (('far', 'normal', 'close'), 'day', 'sl smile2 dress', ('sl/sl_2_body.png', 'sl/sl_2_dress.png', 'sl/sl_2_smile2.png')),
        (('far', 'normal', 'close'), 'day', 'us smile swim', ('us/us_1_body.png', 'us/us_1_swim.png', 'us/us_1_smile.png')),
        (('far', 'normal', 'close'), 'day', 'mt rage panama dress', ('mt/mt_2_body.png', 'mt/mt_2_panama.png', 'mt/mt_2_rage.png', 'mt/mt_2_dress.png')),
        (('far', 'normal', 'close'), 'day', 'dv surprise pioneer2', ('dv/dv_1_body.png', 'dv/dv_1_pioneer2.png', 'dv/dv_1_surprise.png')),
        (('far', 'normal', 'close'), 'day', 'us cry2 sport', ('us/us_3_body.png', 'us/us_3_sport.png', 'us/us_3_cry2.png')),
        (('far', 'normal', 'close'), 'day', 'un normal dress', ('un/un_1_body.png', 'un/un_1_dress.png', 'un/un_1_normal.png')),
        (('far', 'normal', 'close'), 'day', 'mi smile swim', ('mi/mi_2_body.png', 'mi/mi_2_swim.png', 'mi/mi_2_smile.png')),
        (('far', 'normal', 'close'), 'day', 'cs normal glasses', ('cs/cs_1_body.png', 'cs/cs_1_glasses.png', 'cs/cs_1_normal.png')),
        (('far', 'normal', 'close'), 'day', 'uv rage', ('uv/uv_1_body.png', 'uv/uv_1_pioneer.png', 'uv/uv_1_rage.png')),
        (('far', 'normal', 'close'), 'day', 'sl sad dress', ('sl/sl_3_body.png', 'sl/sl_3_dress.png', 'sl/sl_3_sad.png')),
        (('far', 'normal', 'close'), 'day', 'mt rage swim', ('mt/mt_2_body.png', 'mt/mt_2_swim.png', 'mt/mt_2_rage.png')),
        (('far', 'normal', 'close'), 'day', 'dv rage pioneer', ('dv/dv_5_body.png', 'dv/dv_5_pioneer.png', 'dv/dv_5_rage.png')),
        (('far', 'normal', 'close'), 'day', 'el surprise pioneer', ('el/el_2_body.png', 'el/el_2_pioneer.png', 'el/el_2_surprise.png')),
        (('far', 'normal', 'close'), 'day', 'un cry pioneer', ('un/un_2_body.png', 'un/un_2_pioneer.png', 'un/un_2_cry.png')),
        (('far', 'normal', 'close'), 'day', 'mi dontlike pioneer', ('mi/mi_1_body.png', 'mi/mi_1_pioneer.png', 'mi/mi_1_dontlike.png')),
        (('far', 'normal', 'close'), 'day', 'sl shy swim', ('sl/sl_2_body.png', 'sl/sl_2_swim.png', 'sl/sl_2_shy.png')),
        (('far', 'normal', 'close'), 'day', 'el serious pioneer', ('el/el_3_body.png', 'el/el_3_pioneer.png', 'el/el_3_serious.png')),
        (('far', 'normal', 'close'), 'day', 'un scared swim', ('un/un_2_body.png', 'un/un_2_swim.png', 'un/un_2_scared.png')),
        (('far', 'normal', 'close'), 'day', 'el scared pioneer', ('el/el_2_body.png', 'el/el_2_pioneer.png', 'el/el_2_scared.png')),
        (('far', 'normal', 'close'), 'day', 'mi cry swim', ('mi/mi_1_body.png', 'mi/mi_1_swim.png', 'mi/mi_1_cry.png')),
        (('far', 'normal', 'close'), 'day', 'mz smile pioneer', ('mz/mz_3_body.png', 'mz/mz_3_pioneer.png', 'mz/mz_3_smile.png')),
        (('far', 'normal', 'close'), 'day', 'us laugh sport', ('us/us_1_body.png', 'us/us_1_sport.png', 'us/us_1_laugh.png')),
        (('far', 'normal', 'close'), 'day', 'mt surprise dress', ('mt/mt_1_body.png', 'mt/mt_1_dress.png', 'mt/mt_1_surprise.png')),
        (('far', 'normal', 'close'), 'day', 'mt sad panama swim', ('mt/mt_1_body.png', 'mt/mt_1_panama.png', 'mt/mt_1_sad.png', 'mt/mt_1_swim.png')),
        (('far', 'normal', 'close'), 'day', 'sh upset', ('sh/sh_1_body.png', 'sh/sh_1_laugh.png', 'sh/sh_1_upset.png')),
        (('far', 'normal', 'close'), 'day', 'un evil_smile sport', ('un/un_1_body.png', 'un/un_1_sport.png', 'un/un_1_evil_smile.png')),
        (('far', 'normal', 'close'), 'day', 'uv surprise', ('uv/uv_4_body.png', 'uv/uv_4_pioneer.png', 'uv/uv_4_surprise.png')),
        (('far', 'normal', 'close'), 'day', 'el grin pioneer', ('el/el_1_body.png', 'el/el_1_pioneer.png', 'el/el_1_grin.png')),
        (('far', 'normal', 'close'), 'day', 'mt smile swim', ('mt/mt_1_body.png', 'mt/mt_1_swim.png', 'mt/mt_1_smile.png')),
        (('far', 'normal', 'close'), 'day', 'us shy sport', ('us/us_3_body.png', 'us/us_3_sport.png', 'us/us_3_shy.png')),
        (('far', 'normal', 'close'), 'day', 'us fear sport', ('us/us_2_body.png', 'us/us_2_sport.png', 'us/us_2_fear.png')),
        (('far', 'normal', 'close'), 'day', 'un evil_smile pioneer', ('un/un_1_body.png', 'un/un_1_pioneer.png', 'un/un_1_evil_smile.png')),
        (('far', 'normal', 'close'), 'day', 'us laugh2 pioneer', ('us/us_1_body.png', 'us/us_1_pioneer.png', 'us/us_1_laugh2.png')),
        (('far', 'normal', 'close'), 'day', 'sl shy pioneer', ('sl/sl_2_body.png', 'sl/sl_2_pioneer.png', 'sl/sl_2_shy.png')),
        (('far', 'normal', 'close'), 'day', 'us surp3 pioneer', ('us/us_3_body.png', 'us/us_3_pioneer.png', 'us/us_3_surp3.png')),
        (('far', 'normal', 'close'), 'day', 'mi laugh swim', ('mi/mi_1_body.png', 'mi/mi_1_swim.png', 'mi/mi_1_laugh.png')),
        (('far', 'normal', 'close'), 'day', 'un smile3 dress', ('un/un_3_body.png', 'un/un_3_dress.png', 'un/un_3_smile3.png')),
        (('far', 'normal', 'close'), 'day', 'us surp3 swim', ('us/us_3_body.png', 'us/us_3_swim.png', 'us/us_3_surp3.png')),
        (('far', 'normal', 'close'), 'day', 'un grin pioneer', ('un/un_3_body.png', 'un/un_3_pioneer.png', 'un/un_3_grin.png')),
        (('far', 'normal', 'close'), 'day', 'mt laugh panama pioneer', ('mt/mt_3_body.png', 'mt/mt_3_panama.png', 'mt/mt_3_laugh.png', 'mt/mt_3_pioneer.png')),
        (('far', 'normal', 'close'), 'day', 'sl shy dress', ('sl/sl_2_body.png', 'sl/sl_2_dress.png', 'sl/sl_2_shy.png')),
        (('far', 'normal', 'close'), 'day', 'el sad pioneer', ('el/el_2_body.png', 'el/el_2_pioneer.png', 'el/el_2_sad.png')),
        (('far', 'normal', 'close'), 'day', 'un surprise sport', ('un/un_2_body.png', 'un/un_2_sport.png', 'un/un_2_surprise.png')),
        (('far', 'normal', 'close'), 'day', 'mt surprise panama pioneer', ('mt/mt_1_body.png', 'mt/mt_1_panama.png', 'mt/mt_1_surprise.png', 'mt/mt_1_pioneer.png')),
        (('far', 'normal', 'close'), 'day', 'us angry dress', ('us/us_2_body.png', 'us/us_2_dress.png', 'us/us_2_angry.png')),
        (('far', 'normal', 'close'), 'day', 'sl serious sport', ('sl/sl_1_body.png', 'sl/sl_1_sport.png', 'sl/sl_1_serious.png')),
        (('far', 'normal', 'close'), 'day', 'un scared sport', ('un/un_2_body.png', 'un/un_2_sport.png', 'un/un_2_scared.png')),
        (('far', 'normal', 'close'), 'day', 'un cry dress', ('un/un_2_body.png', 'un/un_2_dress.png', 'un/un_2_cry.png')),
        (('far', 'normal', 'close'), 'day', 'dv scared pioneer2', ('dv/dv_1_body.png', 'dv/dv_1_pioneer2.png', 'dv/dv_1_scared.png')),
        (('far', 'normal', 'close'), 'day', 'dv shocked pioneer2', ('dv/dv_1_body.png', 'dv/dv_1_pioneer2.png', 'dv/dv_1_shocked.png')),
        (('far', 'normal', 'close'), 'day', 'sl laugh swim', ('sl/sl_2_body.png', 'sl/sl_2_swim.png', 'sl/sl_2_laugh.png')),
        (('far', 'normal', 'close'), 'day', 'us surp1 dress', ('us/us_3_body.png', 'us/us_3_dress.png', 'us/us_3_surp1.png')),
        (('far', 'normal', 'close'), 'day', 'dv shocked swim', ('dv/dv_1_body.png', 'dv/dv_1_swim.png', 'dv/dv_1_shocked.png')),
        (('far', 'normal', 'close'), 'day', 'sh laugh', ('sh/sh_1_body.png', 'sh/sh_1_laugh.png', 'sh/sh_1_laugh.png')),
        (('far', 'normal', 'close'), 'day', 'us surp2 dress', ('us/us_3_body.png', 'us/us_3_dress.png', 'us/us_3_surp2.png')),
        (('far', 'normal', 'close'), 'day', 'uv sad', ('uv/uv_1_body.png', 'uv/uv_1_pioneer.png', 'uv/uv_1_sad.png')),
        (('far', 'normal', 'close'), 'day', 'el angry pioneer', ('el/el_3_body.png', 'el/el_3_pioneer.png', 'el/el_3_angry.png')),
        (('far', 'normal', 'close'), 'day', 'us cry2 dress', ('us/us_3_body.png', 'us/us_3_dress.png', 'us/us_3_cry2.png')),
        (('far', 'normal', 'close'), 'day', 'sl sad sport', ('sl/sl_3_body.png', 'sl/sl_3_sport.png', 'sl/sl_3_sad.png')),
        (('far', 'normal', 'close'), 'day', 'mi scared swim', ('mi/mi_1_body.png', 'mi/mi_1_swim.png', 'mi/mi_1_scared.png')),
        (('far', 'normal', 'close'), 'day', 'us laugh swim', ('us/us_1_body.png', 'us/us_1_swim.png', 'us/us_1_laugh.png')),
        (('far', 'normal', 'close'), 'day', 'mi surprise swim', ('mi/mi_1_body.png', 'mi/mi_1_swim.png', 'mi/mi_1_surprise.png')),
        (('far', 'normal', 'close'), 'day', 'sl smile swim', ('sl/sl_1_body.png', 'sl/sl_1_swim.png', 'sl/sl_1_smile.png')),
        (('far', 'normal', 'close'), 'day', 'us shy2 dress', ('us/us_3_body.png', 'us/us_3_dress.png', 'us/us_3_shy2.png')),
        (('far', 'normal', 'close'), 'day', 'sl surprise swim', ('sl/sl_3_body.png', 'sl/sl_3_swim.png', 'sl/sl_3_surprise.png')),
        (('far', 'normal', 'close'), 'day', 'dv smile pioneer2', ('dv/dv_4_body.png', 'dv/dv_4_pioneer2.png', 'dv/dv_4_smile.png')),
        (('far', 'normal', 'close'), 'day', 'mt sad dress', ('mt/mt_1_body.png', 'mt/mt_1_dress.png', 'mt/mt_1_sad.png')),
        (('far', 'normal', 'close'), 'day', 'mt smile panama pioneer', ('mt/mt_1_body.png', 'mt/mt_1_panama.png', 'mt/mt_1_smile.png', 'mt/mt_1_pioneer.png')),
        (('far', 'normal', 'close'), 'day', 'dv angry pioneer2', ('dv/dv_5_body.png', 'dv/dv_5_pioneer2.png', 'dv/dv_5_angry.png')),
        (('far', 'normal', 'close'), 'day', 'uv shocked', ('uv/uv_1_body.png', 'uv/uv_1_pioneer.png', 'uv/uv_1_shocked.png')),
        (('far', 'normal', 'close'), 'day', 'mz shy glasses pioneer', ('mz/mz_3_body.png', 'mz/mz_3_glasses.png', 'mz/mz_3_shy.png', 'mz/mz_3_pioneer.png')),
        (('far', 'normal', 'close'), 'day', 'dv sad pioneer2', ('dv/dv_3_body.png', 'dv/dv_3_pioneer2.png', 'dv/dv_3_sad.png')),
        (('far', 'normal', 'close'), 'day', 'us shy dress', ('us/us_3_body.png', 'us/us_3_dress.png', 'us/us_3_shy.png')),
        (('far', 'normal', 'close'), 'day', 'dv normal pioneer', ('dv/dv_4_body.png', 'dv/dv_4_pioneer.png', 'dv/dv_4_normal.png')),
        (('far', 'normal', 'close'), 'day', 'us calml pioneer', ('us/us_2_body.png', 'us/us_2_pioneer.png', 'us/us_2_calml.png')),
        (('far', 'normal', 'close'), 'day', 'mt sad swim', ('mt/mt_1_body.png', 'mt/mt_1_swim.png', 'mt/mt_1_sad.png')),
        (('far', 'normal', 'close'), 'day', 'sl tender dress', ('sl/sl_4_body.png', 'sl/sl_4_dress.png', 'sl/sl_4_tender.png')),
        (('far', 'normal', 'close'), 'day', 'uv dontlike', ('uv/uv_1_body.png', 'uv/uv_1_pioneer.png', 'uv/uv_1_dontlike.png')),
        (('far', 'normal', 'close'), 'day', 'sh surprise', ('sh/sh_3_body.png', 'sh/sh_3_normal.png', 'sh/sh_3_surprise.png')),
        (('far', 'normal', 'close'), 'day', 'us dontlike swim', ('us/us_2_body.png', 'us/us_2_swim.png', 'us/us_2_dontlike.png')),
        (('far', 'normal', 'close'), 'day', 'sl angry pioneer', ('sl/sl_3_body.png', 'sl/sl_3_pioneer.png', 'sl/sl_3_angry.png')),
        (('far', 'normal', 'close'), 'day', 'us shy pioneer', ('us/us_3_body.png', 'us/us_3_pioneer.png', 'us/us_3_shy.png')),
        (('far', 'normal', 'close'), 'day', 'un cry_smile pioneer', ('un/un_2_body.png', 'un/un_2_pioneer.png', 'un/un_2_cry_smile.png')),
        (('far', 'normal', 'close'), 'day', 'un shy pioneer', ('un/un_1_body.png', 'un/un_1_pioneer.png', 'un/un_1_shy.png')),
        (('far', 'normal', 'close'), 'day', 'mt normal panama swim', ('mt/mt_1_body.png', 'mt/mt_1_panama.png', 'mt/mt_1_normal.png', 'mt/mt_1_swim.png')),
        (('far', 'normal', 'close'), 'day', 'sl normal swim', ('sl/sl_1_body.png', 'sl/sl_1_swim.png', 'sl/sl_1_normal.png')),
        (('far', 'normal', 'close'), 'day', 'mz laugh pioneer', ('mz/mz_1_body.png', 'mz/mz_1_pioneer.png', 'mz/mz_1_laugh.png')),
        (('far', 'normal', 'close'), 'day', 'dv surprise swim', ('dv/dv_1_body.png', 'dv/dv_1_swim.png', 'dv/dv_1_surprise.png')),
        (('far', 'normal', 'close'), 'day', 'sl laugh pioneer', ('sl/sl_2_body.png', 'sl/sl_2_pioneer.png', 'sl/sl_2_laugh.png')),
        (('far', 'normal', 'close'), 'day', 'sh laugh pioneer', ('sh/sh_1_body.png', 'sh/sh_1_laugh.png')),
        (('far', 'normal', 'close'), 'day', 'sl smile sport', ('sl/sl_1_body.png', 'sl/sl_1_sport.png', 'sl/sl_1_smile.png')),
        (('far', 'normal', 'close'), 'day', 'sl scared swim', ('sl/sl_4_body.png', 'sl/sl_4_swim.png', 'sl/sl_4_scared.png')),
        (('far', 'normal', 'close'), 'day', 'un scared dress', ('un/un_2_body.png', 'un/un_2_dress.png', 'un/un_2_scared.png')),
        (('far', 'normal', 'close'), 'day', 'sl serious swim', ('sl/sl_1_body.png', 'sl/sl_1_swim.png', 'sl/sl_1_serious.png')),
        (('far', 'normal', 'close'), 'day', 'mt normal dress', ('mt/mt_1_body.png', 'mt/mt_1_dress.png', 'mt/mt_1_normal.png')),
        (('far', 'normal', 'close'), 'day', 'us grin dress', ('us/us_1_body.png', 'us/us_1_dress.png', 'us/us_1_grin.png')),
        (('far', 'normal', 'close'), 'day', 'sl laugh dress', ('sl/sl_2_body.png', 'sl/sl_2_dress.png', 'sl/sl_2_laugh.png')),
        (('far', 'normal', 'close'), 'day', 'us laugh dress', ('us/us_1_body.png', 'us/us_1_dress.png', 'us/us_1_laugh.png')),
        (('far', 'normal', 'close'), 'day', 'dv cry swim', ('dv/dv_1_body.png', 'dv/dv_1_swim.png', 'dv/dv_1_cry.png')),
        (('far', 'normal', 'close'), 'day', 'cs shy stethoscope', ('cs/cs_1_body.png', 'cs/cs_1_stethoscope.png', 'cs/cs_1_shy.png')),
        (('far', 'normal', 'close'), 'day', 'sh upset pioneer', ('sh/sh_1_body.png', 'sh/sh_1_upset.png')),
        (('far', 'normal', 'close'), 'day', 'mz shy pioneer', ('mz/mz_3_body.png', 'mz/mz_3_pioneer.png', 'mz/mz_3_shy.png')),
        (('far', 'normal', 'close'), 'day', 'mz laugh glasses pioneer', ('mz/mz_1_body.png', 'mz/mz_1_glasses.png', 'mz/mz_1_laugh.png', 'mz/mz_1_pioneer.png')),
        (('far', 'normal', 'close'), 'day', 'mz normal glasses pioneer', ('mz/mz_1_body.png', 'mz/mz_1_glasses.png', 'mz/mz_1_normal.png', 'mz/mz_1_pioneer.png')),
        (('far', 'normal', 'close'), 'day', 'cs shy', ('cs/cs_1_body.png', 'cs/cs_1_shy.png')),
        (('far', 'close'), 'day', 'pi', ('pi/pi_1_pioneer.png',)),
        (('far', 'normal', 'close'), 'day', 'mz bukal glasses pioneer', ('mz/mz_1_body.png', 'mz/mz_1_glasses.png', 'mz/mz_1_bukal.png', 'mz/mz_1_pioneer.png')),
        (('far', 'normal', 'close'), 'day', 'mi rage pioneer', ('mi/mi_3_body.png', 'mi/mi_3_pioneer.png', 'mi/mi_3_rage.png')),
        (('far', 'normal', 'close'), 'day', 'sl normal pioneer', ('sl/sl_1_body.png', 'sl/sl_1_pioneer.png', 'sl/sl_1_normal.png')),
        (('far', 'normal', 'close'), 'day', 'mi rage swim', ('mi/mi_3_body.png', 'mi/mi_3_swim.png', 'mi/mi_3_rage.png')),
        (('far', 'normal', 'close'), 'day', 'el upset pioneer', ('el/el_2_body.png', 'el/el_2_pioneer.png', 'el/el_2_upset.png')),
        (('far', 'normal', 'close'), 'day', 'us normal pioneer', ('us/us_1_body.png', 'us/us_1_pioneer.png', 'us/us_1_normal.png')),
        (('far', 'normal', 'close'), 'day', 'un shy dress', ('un/un_1_body.png', 'un/un_1_dress.png', 'un/un_1_shy.png')),
        (('far', 'normal', 'close'), 'day', 'mt surprise panama swim', ('mt/mt_1_body.png', 'mt/mt_1_panama.png', 'mt/mt_1_surprise.png', 'mt/mt_1_swim.png')),
        (('far', 'normal', 'close'), 'day', 'us sad sport', ('us/us_1_body.png', 'us/us_1_sport.png', 'us/us_1_sad.png')),
        (('far', 'normal', 'close'), 'day', 'mi angry swim', ('mi/mi_3_body.png', 'mi/mi_3_swim.png', 'mi/mi_3_angry.png')),
        (('far', 'normal', 'close'), 'day', 'sl happy pioneer', ('sl/sl_2_body.png', 'sl/sl_2_pioneer.png', 'sl/sl_2_happy.png')),
        (('far', 'normal', 'close'), 'day', 'mt sad panama pioneer', ('mt/mt_1_body.png', 'mt/mt_1_panama.png', 'mt/mt_1_sad.png', 'mt/mt_1_pioneer.png')),
        (('far', 'normal', 'close'), 'day', 'us calml sport', ('us/us_2_body.png', 'us/us_2_sport.png', 'us/us_2_calml.png')),
        (('far', 'normal', 'close'), 'day', 'us shy2 pioneer', ('us/us_3_body.png', 'us/us_3_pioneer.png', 'us/us_3_shy2.png')),
        (('far', 'normal', 'close'), 'day', 'un surprise pioneer', ('un/un_2_body.png', 'un/un_2_pioneer.png', 'un/un_2_surprise.png')),
        (('far', 'normal', 'close'), 'day', 'us cry sport', ('us/us_3_body.png', 'us/us_3_sport.png', 'us/us_3_cry.png')),
        (('far', 'normal', 'close'), 'day', 'mi angry pioneer', ('mi/mi_3_body.png', 'mi/mi_3_pioneer.png', 'mi/mi_3_angry.png')),
        (('far', 'normal', 'close'), 'day', 'us sad pioneer', ('us/us_1_body.png', 'us/us_1_pioneer.png', 'us/us_1_sad.png')),
        (('far', 'normal', 'close'), 'day', 'uv smile', ('uv/uv_2_body.png', 'uv/uv_2_pioneer.png', 'uv/uv_2_smile.png')),
        (('far', 'normal', 'close'), 'day', 'un cry swim', ('un/un_2_body.png', 'un/un_2_swim.png', 'un/un_2_cry.png')),
        (('far', 'normal', 'close'), 'day', 'sh normal pioneer', ('sh/sh_3_body.png', 'sh/sh_3_normal.png')),
        (('far', 'normal', 'close'), 'day', 'sh rage', ('sh/sh_2_body.png', 'sh/sh_2_rage.png', 'sh/sh_2_rage.png')),
        (('far', 'normal', 'close'), 'day', 'us normal sport', ('us/us_1_body.png', 'us/us_1_sport.png', 'us/us_1_normal.png')),
        (('far', 'normal', 'close'), 'day', 'un angry2 sport', ('un/un_3_body.png', 'un/un_3_sport.png', 'un/un_3_angry2.png')),
        (('far', 'normal', 'close'), 'day', 'sl happy swim', ('sl/sl_2_body.png', 'sl/sl_2_swim.png', 'sl/sl_2_happy.png')),
        (('far', 'normal', 'close'), 'day', 'mz rage glasses pioneer', ('mz/mz_2_body.png', 'mz/mz_2_glasses.png', 'mz/mz_2_rage.png', 'mz/mz_2_pioneer.png')),
        (('far', 'normal', 'close'), 'day', 'us smile pioneer', ('us/us_1_body.png', 'us/us_1_pioneer.png', 'us/us_1_smile.png')),
        (('far', 'normal', 'close'), 'day', 'mt angry panama swim', ('mt/mt_2_body.png', 'mt/mt_2_panama.png', 'mt/mt_2_angry.png', 'mt/mt_2_swim.png')),
        (('far', 'normal', 'close'), 'day', 'sh cry pioneer', ('sh/sh_2_body.png', 'sh/sh_2_cry.png')),
        (('far', 'normal', 'close'), 'day', 'mz smile glasses pioneer', ('mz/mz_3_body.png', 'mz/mz_3_glasses.png', 'mz/mz_3_smile.png', 'mz/mz_3_pioneer.png')),
        (('far', 'normal', 'close'), 'day', 'sh scared pioneer', ('sh/sh_1_body.png', 'sh/sh_1_scared.png')),
        (('far', 'normal', 'close'), 'day', 'mi upset pioneer', ('mi/mi_3_body.png', 'mi/mi_3_pioneer.png', 'mi/mi_3_upset.png')),
        (('far', 'normal', 'close'), 'day', 'mi upset swim', ('mi/mi_3_body.png', 'mi/mi_3_swim.png', 'mi/mi_3_upset.png')),
        (('far', 'normal', 'close'), 'day', 'us normal swim', ('us/us_1_body.png', 'us/us_1_swim.png', 'us/us_1_normal.png')),
        (('far', 'normal', 'close'), 'day', 'sh normal', ('sh/sh_3_body.png', 'sh/sh_3_normal.png', 'sh/sh_3_normal.png')),
        (('far', 'normal', 'close'), 'day', 'un shocked dress', ('un/un_2_body.png', 'un/un_2_dress.png', 'un/un_2_shocked.png')),
        (('far', 'normal', 'close'), 'day', 'un angry sport', ('un/un_1_body.png', 'un/un_1_sport.png', 'un/un_1_angry.png')),
        (('far', 'normal', 'close'), 'day', 'el smile pioneer', ('el/el_1_body.png', 'el/el_1_pioneer.png', 'el/el_1_smile.png')),
        (('far', 'normal', 'close'), 'day', 'mi cry_smile swim', ('mi/mi_2_body.png', 'mi/mi_2_swim.png', 'mi/mi_2_cry_smile.png')),
        (('far', 'normal', 'close'), 'day', 'mi grin pioneer', ('mi/mi_2_body.png', 'mi/mi_2_pioneer.png', 'mi/mi_2_grin.png')),
        (('far', 'normal', 'close'), 'day', 'sl scared dress', ('sl/sl_4_body.png', 'sl/sl_4_dress.png', 'sl/sl_4_scared.png')),
        (('far', 'normal', 'close'), 'day', 'un cry_smile dress', ('un/un_2_body.png', 'un/un_2_dress.png', 'un/un_2_cry_smile.png')),
        (('far', 'normal', 'close'), 'day', 'un cry_smile sport', ('un/un_2_body.png', 'un/un_2_sport.png', 'un/un_2_cry_smile.png')),
        (('far', 'normal', 'close'), 'day', 'un sad sport', ('un/un_2_body.png', 'un/un_2_sport.png', 'un/un_2_sad.png')),
        (('far', 'normal', 'close'), 'day', 'mt surprise panama dress', ('mt/mt_1_body.png', 'mt/mt_1_panama.png', 'mt/mt_1_surprise.png', 'mt/mt_1_dress.png')),
        (('far', 'normal', 'close'), 'day', 'dv normal pioneer2', ('dv/dv_4_body.png', 'dv/dv_4_pioneer2.png', 'dv/dv_4_normal.png')),
        (('far', 'normal', 'close'), 'day', 'mz angry glasses pioneer', ('mz/mz_2_body.png', 'mz/mz_2_glasses.png', 'mz/mz_2_angry.png', 'mz/mz_2_pioneer.png')),
        (('far', 'normal', 'close'), 'day', 'us cry2 pioneer', ('us/us_3_body.png', 'us/us_3_pioneer.png', 'us/us_3_cry2.png')),
        (('far', 'normal', 'close'), 'day', 'mi sad swim', ('mi/mi_2_body.png', 'mi/mi_2_swim.png', 'mi/mi_2_sad.png')),
        (('far', 'normal', 'close'), 'day', 'un sad swim', ('un/un_2_body.png', 'un/un_2_swim.png', 'un/un_2_sad.png')),
        (('far', 'normal', 'close'), 'day', 'us laugh2 sport', ('us/us_1_body.png', 'us/us_1_sport.png', 'us/us_1_laugh2.png')),
        (('far', 'normal', 'close'), 'day', 'dv angry pioneer', ('dv/dv_5_body.png', 'dv/dv_5_pioneer.png', 'dv/dv_5_angry.png')),
        (('far', 'normal', 'close'), 'day', 'mt smile pioneer', ('mt/mt_1_body.png', 'mt/mt_1_pioneer.png', 'mt/mt_1_smile.png')),
        (('far', 'normal', 'close'), 'day', 'mi shy swim', ('mi/mi_1_body.png', 'mi/mi_1_swim.png', 'mi/mi_1_shy.png')),
        (('far', 'normal', 'close'), 'day', 'un grin dress', ('un/un_3_body.png', 'un/un_3_dress.png', 'un/un_3_grin.png')),
        (('far', 'normal', 'close'), 'day', 'mt laugh pioneer', ('mt/mt_3_body.png', 'mt/mt_3_pioneer.png', 'mt/mt_3_laugh.png')),
        (('far', 'normal', 'close'), 'day', 'un laugh pioneer', ('un/un_3_body.png', 'un/un_3_pioneer.png', 'un/un_3_laugh.png')),
        (('far', 'normal', 'close'), 'day', 'dv laugh pioneer2', ('dv/dv_4_body.png', 'dv/dv_4_pioneer2.png', 'dv/dv_4_laugh.png')),
        (('far', 'normal', 'close'), 'day', 'us surp1 pioneer', ('us/us_3_body.png', 'us/us_3_pioneer.png', 'us/us_3_surp1.png')),
        (('far', 'normal', 'close'), 'day', 'sh rage pioneer', ('sh/sh_2_body.png', 'sh/sh_2_rage.png')),
        (('far', 'normal', 'close'), 'day', 'mt angry panama dress', ('mt/mt_2_body.png', 'mt/mt_2_panama.png', 'mt/mt_2_angry.png', 'mt/mt_2_dress.png')),
        (('far', 'normal', 'close'), 'day', 'un shocked swim', ('un/un_2_body.png', 'un/un_2_swim.png', 'un/un_2_shocked.png')),
        (('far', 'normal', 'close'), 'day', 'un evil_smile dress', ('un/un_1_body.png', 'un/un_1_dress.png', 'un/un_1_evil_smile.png')),
        (('far', 'normal', 'close'), 'day', 'uv laugh', ('uv/uv_3_body.png', 'uv/uv_3_pioneer.png', 'uv/uv_3_laugh.png')),
        (('far', 'normal', 'close'), 'day', 'dv scared swim', ('dv/dv_1_body.png', 'dv/dv_1_swim.png', 'dv/dv_1_scared.png')),
        (('far', 'normal', 'close'), 'day', 'mi shocked swim', ('mi/mi_1_body.png', 'mi/mi_1_swim.png', 'mi/mi_1_shocked.png')),
        (('far', 'normal', 'close'), 'day', 'mt angry pioneer', ('mt/mt_2_body.png', 'mt/mt_2_pioneer.png', 'mt/mt_2_angry.png')),
        (('far', 'normal', 'close'), 'day', 'el fingal pioneer', ('el/el_2_body.png', 'el/el_2_pioneer.png', 'el/el_2_fingal.png')),
        (('far', 'normal', 'close'), 'day', 'us surp3 sport', ('us/us_3_body.png', 'us/us_3_sport.png', 'us/us_3_surp3.png')),
        (('far', 'normal', 'close'), 'day', 'sl happy dress', ('sl/sl_2_body.png', 'sl/sl_2_dress.png', 'sl/sl_2_happy.png')),
        (('far', 'normal', 'close'), 'day', 'sh scared', ('sh/sh_1_body.png', 'sh/sh_1_laugh.png', 'sh/sh_1_scared.png')),
        (('far', 'normal', 'close'), 'day', 'un angry2 pioneer', ('un/un_3_body.png', 'un/un_3_pioneer.png', 'un/un_3_angry2.png')),
        (('far', 'normal', 'close'), 'day', 'uv grin', ('uv/uv_3_body.png', 'uv/uv_3_pioneer.png', 'uv/uv_3_grin.png')),
        (('far', 'normal', 'close'), 'day', 'mi shy pioneer', ('mi/mi_1_body.png', 'mi/mi_1_pioneer.png', 'mi/mi_1_shy.png')),
        (('far', 'normal', 'close'), 'day', 'sl sad pioneer', ('sl/sl_3_body.png', 'sl/sl_3_pioneer.png', 'sl/sl_3_sad.png')),
        (('far', 'normal', 'close'), 'day', 'un smile2 sport', ('un/un_1_body.png', 'un/un_1_sport.png', 'un/un_1_smile2.png')),
        (('far', 'normal', 'close'), 'day', 'us cry dress', ('us/us_3_body.png', 'us/us_3_dress.png', 'us/us_3_cry.png')),
        (('far', 'normal', 'close'), 'day', 'un rage pioneer', ('un/un_3_body.png', 'un/un_3_pioneer.png', 'un/un_3_rage.png')),
        (('far', 'normal', 'close'), 'day', 'sl sad swim', ('sl/sl_3_body.png', 'sl/sl_3_swim.png', 'sl/sl_3_sad.png')),
        (('far', 'normal', 'close'), 'day', 'mi normal pioneer', ('mi/mi_3_body.png', 'mi/mi_3_pioneer.png', 'mi/mi_3_normal.png')),
        (('far', 'normal', 'close'), 'day', 'us surp1 sport', ('us/us_3_body.png', 'us/us_3_sport.png', 'us/us_3_surp1.png')),
        (('far', 'normal', 'close'), 'day', 'us cry swim', ('us/us_3_body.png', 'us/us_3_swim.png', 'us/us_3_cry.png')),
        (('far', 'normal', 'close'), 'day', 'un serious dress', ('un/un_3_body.png', 'un/un_3_dress.png', 'un/un_3_serious.png')),
        (('far', 'normal', 'close'), 'day', 'un laugh sport', ('un/un_3_body.png', 'un/un_3_sport.png', 'un/un_3_laugh.png')),
        (('far', 'normal', 'close'), 'day', 'un surprise dress', ('un/un_2_body.png', 'un/un_2_dress.png', 'un/un_2_surprise.png')),
        (('far', 'normal', 'close'), 'day', 'mi happy swim', ('mi/mi_2_body.png', 'mi/mi_2_swim.png', 'mi/mi_2_happy.png')),
        (('far', 'normal', 'close'), 'day', 'mi serious swim', ('mi/mi_3_body.png', 'mi/mi_3_swim.png', 'mi/mi_3_serious.png')),
        (('far', 'normal', 'close'), 'day', 'uv surprise2', ('uv/uv_3_body.png', 'uv/uv_3_pioneer.png', 'uv/uv_3_surprise2.png')),
        (('far', 'normal', 'close'), 'day', 'mz angry pioneer', ('mz/mz_2_body.png', 'mz/mz_2_pioneer.png', 'mz/mz_2_angry.png')),
        (('far', 'normal', 'close'), 'day', 'un sad pioneer', ('un/un_2_body.png', 'un/un_2_pioneer.png', 'un/un_2_sad.png')),
        (('far', 'normal', 'close'), 'day', 'dv surprise pioneer', ('dv/dv_1_body.png', 'dv/dv_1_pioneer.png', 'dv/dv_1_surprise.png')),
        (('far', 'normal', 'close'), 'day', 'mz bukal pioneer', ('mz/mz_1_body.png', 'mz/mz_1_pioneer.png', 'mz/mz_1_bukal.png')),
        (('far', 'normal', 'close'), 'day', 'mi shocked pioneer', ('mi/mi_1_body.png', 'mi/mi_1_pioneer.png', 'mi/mi_1_shocked.png')),
        (('far', 'normal', 'close'), 'day', 'sl happy sport', ('sl/sl_2_body.png', 'sl/sl_2_sport.png', 'sl/sl_2_happy.png')),
        (('far', 'normal', 'close'), 'day', 'un sad dress', ('un/un_2_body.png', 'un/un_2_dress.png', 'un/un_2_sad.png')),
        (('far', 'normal', 'close'), 'day', 'dv cry pioneer', ('dv/dv_1_body.png', 'dv/dv_1_pioneer.png', 'dv/dv_1_cry.png')),
        (('far', 'normal', 'close'), 'day', 'sl angry swim', ('sl/sl_3_body.png', 'sl/sl_3_swim.png', 'sl/sl_3_angry.png')),
        (('far', 'normal', 'close'), 'day', 'un rage dress', ('un/un_3_body.png', 'un/un_3_dress.png', 'un/un_3_rage.png')),
        (('far', 'normal', 'close'), 'day', 'us normal dress', ('us/us_1_body.png', 'us/us_1_dress.png', 'us/us_1_normal.png')),
        (('far', 'normal', 'close'), 'day', 'sl angry sport', ('sl/sl_3_body.png', 'sl/sl_3_sport.png', 'sl/sl_3_angry.png')),
        (('far', 'normal', 'close'), 'day', 'us fear pioneer', ('us/us_2_body.png', 'us/us_2_pioneer.png', 'us/us_2_fear.png')),
        (('far', 'normal', 'close'), 'day', 'mt normal panama dress', ('mt/mt_1_body.png', 'mt/mt_1_panama.png', 'mt/mt_1_normal.png', 'mt/mt_1_dress.png')),
        (('far', 'normal', 'close'), 'day', 'mi serious pioneer', ('mi/mi_3_body.png', 'mi/mi_3_pioneer.png', 'mi/mi_3_serious.png')),
        (('far', 'normal', 'close'), 'day', 'un shocked pioneer', ('un/un_2_body.png', 'un/un_2_pioneer.png', 'un/un_2_shocked.png')),
        (('far', 'normal', 'close'), 'day', 'dv grin pioneer2', ('dv/dv_2_body.png', 'dv/dv_2_pioneer2.png', 'dv/dv_2_grin.png')),
        (('far', 'normal', 'close'), 'day', 'dv grin pioneer', ('dv/dv_2_body.png', 'dv/dv_2_pioneer.png', 'dv/dv_2_grin.png')),
        (('far', 'normal', 'close'), 'day', 'mt rage dress', ('mt/mt_2_body.png', 'mt/mt_2_dress.png', 'mt/mt_2_rage.png')),
        (('far', 'normal', 'close'), 'day', 'us angry sport', ('us/us_2_body.png', 'us/us_2_sport.png', 'us/us_2_angry.png')),
        (('far', 'normal', 'close'), 'day', 'mi grin swim', ('mi/mi_2_body.png', 'mi/mi_2_swim.png', 'mi/mi_2_grin.png')),
        (('far', 'normal', 'close'), 'day', 'mt angry swim', ('mt/mt_2_body.png', 'mt/mt_2_swim.png', 'mt/mt_2_angry.png')),
        (('far', 'normal', 'close'), 'day', 'un surprise swim', ('un/un_2_body.png', 'un/un_2_swim.png', 'un/un_2_surprise.png')),
        (('far', 'normal', 'close'), 'day', 'el shocked pioneer', ('el/el_2_body.png', 'el/el_2_pioneer.png', 'el/el_2_shocked.png')),
        (('far', 'normal', 'close'), 'day', 'us calml dress', ('us/us_2_body.png', 'us/us_2_dress.png', 'us/us_2_calml.png')),
        (('far', 'normal', 'close'), 'day', 'us surp3 dress', ('us/us_3_body.png', 'us/us_3_dress.png', 'us/us_3_surp3.png')),
        (('far', 'normal', 'close'), 'day', 'un smile swim', ('un/un_1_body.png', 'un/un_1_swim.png', 'un/un_1_smile.png')),
        (('far', 'normal', 'close'), 'day', 'mi surprise pioneer', ('mi/mi_1_body.png', 'mi/mi_1_pioneer.png', 'mi/mi_1_surprise.png')),
        (('normal',), 'red', 'un normal pioneer red', ('un/un_1_body.png', 'un/un_1_pioneer.png', 'un/un_1_normal.png')),
        (('normal',), 'day', 'pi normal', ('pi/pi_1_pioneer.png',)),
        (('normal',), 'red', 'un surprise pioneer red', ('un/un_2_body.png', 'un/un_2_pioneer.png', 'un/un_2_surprise.png')),
        (('normal',), 'day', 'mt scared pioneer', ('mt/mt_3_body.png', 'mt/mt_3_pioneer.png', 'mt/mt_3_scared.png')),
        (('normal',), 'day', 'mt shocked pioneer', ('mt/mt_2_body.png', 'mt/mt_2_pioneer.png', 'mt/mt_2_shocked.png')),
        (('normal', 'close'), 'night', 'un normal body', ('un/un_1_body.png', 'un/un_1_normal.png')),
        (('normal', 'close'), 'night', 'un smile body', ('un/un_1_body.png', 'un/un_1_smile.png')),
        (('normal', 'close'), 'night', 'un shy body', ('un/un_1_body.png', 'un/un_1_shy.png')),
        (('normal', 'close'), 'night', 'un surprise body', ('un/un_2_body.png', 'un/un_2_surprise.png')),
        (('normal', 'close'), 'night', 'un angry body', ('un/un_1_body.png', 'un/un_1_angry.png')),
        (('normal', 'close'), 'night', 'un angry2 body', ('un/un_3_body.png', 'un/un_3_angry2.png')),
        (('normal', 'close'), 'night', 'un cry body', ('un/un_2_body.png', 'un/un_2_cry.png')),
        (('normal', 'close'), 'night', 'un grin body', ('un/un_3_body.png', 'un/un_3_grin.png')),
        (('normal', 'close'), 'night', 'un laugh body', ('un/un_3_body.png', 'un/un_3_laugh.png')),
        (('normal', 'close'), 'night', 'un rage body', ('un/un_3_body.png', 'un/un_3_rage.png')),
        (('normal', 'close'), 'night', 'un scared body', ('un/un_2_body.png', 'un/un_2_scared.png')),
        (('normal', 'close'), 'night', 'un shocked body', ('un/un_2_body.png', 'un/un_2_shocked.png')),
        (('normal', 'close'), 'night', 'un smile2 body', ('un/un_1_body.png', 'un/un_1_smile2.png')),
        (('normal', 'close'), 'night', 'un smile3 body', ('un/un_3_body.png', 'un/un_3_smile3.png')),
        (('normal', 'close'), 'night', 'un sad body', ('un/un_2_body.png', 'un/un_2_sad.png')),
        (('normal', 'close'), 'night', 'un evil_smile body', ('un/un_1_body.png', 'un/un_1_evil_smile.png')),
        (('normal', 'close'), 'night', 'un cry_smile body', ('un/un_2_body.png', 'un/un_2_cry_smile.png')),
        (('normal', 'close'), 'night', 'un serious body', ('un/un_3_body.png', 'un/un_3_serious.png')),
        (('normal', 'close'), 'plain', 'dv scared body', ('dv/dv_1_body.png', 'dv/dv_1_scared.png')),
        (('normal', 'close'), 'plain', 'dv sad body', ('dv/dv_3_body.png', 'dv/dv_3_sad.png')),
        (('normal', 'close'), 'plain', 'dv guilty body', ('dv/dv_3_body.png', 'dv/dv_3_guilty.png')),
        (('normal', 'close'), 'plain', 'dv laugh body', ('dv/dv_4_body.png', 'dv/dv_4_laugh.png')),
        (('normal', 'close'), 'plain', 'dv shy body', ('dv/dv_3_body.png', 'dv/dv_3_shy.png')),
        (('normal', 'close'), 'plain', 'dv smile body', ('dv/dv_4_body.png', 'dv/dv_4_smile.png')),
        (('normal', 'close'), 'plain', 'dv shocked body', ('dv/dv_1_body.png', 'dv/dv_1_shocked.png')),
        (('normal', 'close'), 'plain', 'dv rage body', ('dv/dv_5_body.png', 'dv/dv_5_rage.png')),
        (('normal', 'close'), 'plain', 'dv normal body', ('dv/dv_4_body.png', 'dv/dv_4_normal.png')),
        (('normal', 'close'), 'plain', 'dv angry body', ('dv/dv_5_body.png', 'dv/dv_5_angry.png')),
        (('normal', 'close'), 'plain', 'dv surprise body', ('dv/dv_1_body.png', 'dv/dv_1_surprise.png')),
        (('normal', 'close'), 'plain', 'dv cry body', ('dv/dv_1_body.png', 'dv/dv_1_cry.png')),
        (('normal', 'close'), 'plain', 'dv grin body', ('dv/dv_2_body.png', 'dv/dv_2_grin.png')),
        (('normal',), 'night', 'un night', ('un/un_1_body.png', 'un/un_1_pioneer.png', 'un/un_1_shy.png')),
        (('normal',), 'day', 'pi smile', ('pi/pi_1_pioneer_smile.png',)),
    ]

    for _row in SPRITES:
        register_sprite(*_row)
